language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t afif1400/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true afif1400/docker-react npm run test
